//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int FilmId { get; set; }
        public string FilmName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ShowDate { get; set; }
        public Nullable<int> GenreId { get; set; }
        public string CardAccess { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
